### ISSUE TITLE
CI link (and CI builds) now broken

### ISSUE THREAD

**Issue by rosswilson** [ninjaframework/ninja-appengine#18]
CloudBees has shutdown its free CI service. Is there an alternative CI that can be used?

> Sorry, we are no longer hosting free builds on BuildHive, but we are working on something new.
> https://buildhive.cloudbees.com/job/ninjaframework/job/ninja-appengine

**Comment by raphaelbauer** [comment]
Hey Ross... good catch... we'll switch to travis asap...

**Comment by raphaelbauer** [comment]
done... closing now.. thanks for the report!
