### ISSUE TITLE
Keeping App Running when Console is Closed

### ISSUE THREAD

**Issue by iamalotaibi** [ninjaframework/ninja-appengine#26]
**Case:**
I have run the app by using command line then it worked perfectly, however, when I close the command line I get "502 Bag Gateway", which means the app stopped from working.

**Solution:**
Is there a functionality similar to PM2 for Node.js? As PM2 allows apps to keep running in the background without the need for command line to be on.

**Comment by raphaelbauer** [comment]
Ninja - or the JVM ecosystem in general works a bit different. One of the big selling points of PM2 is also that it handles errors and makes sure the single threaded Node app does not simply die after an exception. All that is not needed on the JVM and Ninja's programming model.

We described some ways how you can deploy a Ninja app here: http://www.ninjaframework.org/documentation/deployment/getting_started.html (also read the subpages).

But Ninja deployments are not really special. Anything that works with the JVM will likely also work with Ninja deployments.

**Comment by iamalotaibi** [comment]
I couldn't find anything in the documentations that helps me deploying my app without the need of a running command line on. I have visited the cloud hosting option, and there aren't any information of deploying the app as I am using DigitalOcean to host my site and my app.
  
I am just trying to run the app without the need for the command line to be on all the time. Is there anyway I could accomplish that?
